### ISSUE TITLE
Initial view

### ISSUE THREAD

**Issue by erictzeng** [CS169-Raxa/raxa-visualizations#1]
From the requirements doc:

> Initial view, even if just a front page screen, deployed to Heroku, with a visual appearance that isn't embarrassing.  Plenty of prepackaged CSS templates and themes are available on the Web if you don't feel your design skills are up to snuff.

We'll worry about deploying to Heroku later, but we definitely need to make the initial view.

**Comment by seshness** [comment]
Claiming with intention of finishing this in the next hour-ish.

**Comment by seshness** [comment]
Was meddling with more rails things; taking some more time on this.
