### ISSUE TITLE
Tag for Iter1-1

### ISSUE THREAD

**Issue by erictzeng** [CS169-Raxa/raxa-visualizations#15]
Again, depends on #11 and #12.

We need to tag for submission. From the requirements doc:

> We should be able to run your tests from a fresh clone using the following commands:
> - git checkout iterationi-j
> - bundle install --without production
> - rake db:migrate db:test:prepare db:seed
> - rake cucumber
> - rake spec

Please perform this sanity check right after tagging to ensure that everything went as expected.

**Comment by seshness** [comment]
Sanity check looks good to me.

Cucumber steps are mostly unimplemented/pending.

Rspec tests are pending.
