### ISSUE TITLE
Seeds are broken with Ruby 1.9.2

### ISSUE THREAD

**Issue by danwang** [CS169-Raxa/raxa-visualizations#20]
Using a fresh clone of the repo, I ran the following commands:

```
rvm use 1.9.2
rake db:migrate
rake db:seed
```

Here's the error for `rake db:seed`:

```
(in /home/danwang/src/raxa-visualizations)
/home/danwang/src/raxa-visualizations/db/seed/pharmacy/data/drug1.yaml
rake aborted!
undefined method `documents' for #<Array:0x00000003493038>

Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

It looks like `YAML.load_stream` returns an array for me. Tried in irb:

```
1.9.3-p194 > y = YAML.load_stream(File.open('/home/danwang/src/raxa-visualizations/db/seed/pharmacy/data/drug1.yaml'))
 => ...
1.9.3-p194 > y.class
 => Array
```

Does anyone else have a similar error?

**Comment by danwang** [comment]
I have been able to get `rake db:seed` working by removing the `documents` method call.

**Comment by erictzeng** [comment]
Can't reproduce. :(

```
irb(main):005:0> y = YAML.load_stream(File.open('drug1.yaml'))
=> ...
irb(main):006:0> y.class
=> Syck::Stream
```

I'm using the provided VM, if that makes any difference.

Also, your prompt claims to be running 1.9.3, not 1.9.2. Again, not sure if that makes a difference.
