### ISSUE TITLE
Registration models

### ISSUE THREAD

**Issue by erictzeng** [CS169-Raxa/raxa-visualizations#54]
Here are my thoughts on registration models:

Models:
- Patient
- Registrar
- Registration

Associations:
- A Patient has many Registrations. (One per visit).
- A Registrar has many Registrations. (One per per patient registered).

As for what those information those models contain:

Patients have:
- A name

Registrars have:
- A name

Registrations have:
- A time started
- A time ended
- A Patient (handled by the belongs_to association)
- The patient's status (new or returning)
- A Registrar (handled by the belongs_to association)

Comments appreciated.

**Comment by erictzeng** [comment]
Last call for comments. I'm going to push this soon.

**Comment by danwang** [comment]
Weren't we going to handle things like the path that a patient takes? Would that be handled during a registration?

**Comment by erictzeng** [comment]
When you register a patient, I don't think you know what path he or she will take.

I think the best you could do for generating a path is to collect all events from all departments and use the timestamp to order them into a path. Seems hard to manage that from the registration models.

**Comment by seshness** [comment]
Do we need the registrar information? We don't have it anywhere on our lo-fi UI mockups.

On paths through the system: we talked about that in the context of the superuser. We can add more fields to our model if required later.

**Comment by erictzeng** [comment]
Our mockup was for a single-user dashboard. At least, that's the impression I had of it.

Since we don't have a auth system, I was thinking we could just provide a page with links to each individual Registrar's dashboard. We could provide a link at the top to an overall dashboard, too? Maybe.
