### ISSUE TITLE
Visual feedback on Pharmacy AJAX form submit

### ISSUE THREAD

**Issue by erictzeng** [CS169-Raxa/raxa-visualizations#55]
It'd be nice if the forms on the Pharmacy view displayed a message notifying you that it was submitted. The way it is right now is confusing.

**Comment by seshness** [comment]
Ideally the submit would update an element in the DOM. As a fallback
for non-JS browsers we could refresh the page on a form submit.

**Comment by danwang** [comment]
I'll take this.

**Comment by erictzeng** [comment]
Resolved by #56.
